// Copyright (c) Dropbox, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package contenthash_test

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dropbox/dropbox-sdk-go-unofficial/v6/dropbox/contenthash"
)

func TestComputeKnownVectors(t *testing.T) {
	for _, test := range []struct {
		name string
		data string
		want string
	}{
		{
			name: "empty",
			data: "",
			want: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		},
		{
			name: "single byte",
			data: "a",
			want: "bf5d3affb73efd2ec6c36ad3112dd933efed63c4e1cbffcfa88e2759c144f2d8",
		},
		{
			name: "short string",
			data: "abc",
			want: "4f8b42c22dd3729b519ba6f68d2da7cc5b2d606d05daed5ad5128cc03e6c6358",
		},
		{
			name: "longer string",
			data: "hello world",
			want: "bc62d4b80d9e36da29c16c5d4d9f11731f36052c72401a76c23c0fb5a9b74423",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			got, err := contenthash.Compute(strings.NewReader(test.data))
			if err != nil {
				t.Fatalf("Compute returned error: %v", err)
			}
			if got != test.want {
				t.Fatalf("Compute = %q, want %q", got, test.want)
			}
		})
	}
}

func TestComputeFixtureFiles(t *testing.T) {
	// Expected values are generated by the Python reference implementation from
	// dropbox/dropbox-api-content-hasher.
	for _, test := range []struct {
		name string
		file string
		want string
	}{
		{
			name: "text",
			file: "sample.txt",
			want: "3aeba6e0b3990896935c7cbbf252042893f457669b6019212e8adfe04da21d00",
		},
		{
			name: "pdf",
			file: "sample.pdf",
			want: "a769ae23932c54345ba2174b1437a5da86599e9f1f20160ce5b30aeb1f1b1474",
		},
		{
			name: "jpg",
			file: "sample.jpg",
			want: "ccef29df6adc79e4f3305e066dbc0138fd005c4052722d4e89bbc085c220fee2",
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			f, err := os.Open(filepath.Join("testdata", "content_hash", test.file))
			if err != nil {
				t.Fatalf("open fixture: %v", err)
			}
			defer f.Close()

			got, err := contenthash.Compute(f)
			if err != nil {
				t.Fatalf("Compute returned error: %v", err)
			}
			if got != test.want {
				t.Fatalf("Compute = %q, want %q", got, test.want)
			}
		})
	}
}

func TestHasherChunkBoundaries(t *testing.T) {
	blockSize := contenthash.BlockSize
	tests := [][]int{
		{0},
		{100},
		{100, 10},
		{blockSize - 1},
		{blockSize},
		{blockSize + 1},
		{blockSize - 2, 1},
		{blockSize - 2, 2},
		{blockSize - 2, 3},
		{5, 5, 5, blockSize},
		{blockSize + 1, blockSize - 1, 7},
	}

	data := deterministicBytes(longestTotal(tests))
	for _, chunks := range tests {
		t.Run(fmt.Sprint(chunks), func(t *testing.T) {
			h := contenthash.New()
			pos := 0
			for _, chunkSize := range chunks {
				n, err := h.Write(data[pos : pos+chunkSize])
				if err != nil {
					t.Fatalf("Write returned error: %v", err)
				}
				if n != chunkSize {
					t.Fatalf("Write returned %d, want %d", n, chunkSize)
				}
				pos += chunkSize
			}

			got := h.HexDigest()
			want := referenceContentHash(data[:pos])
			if got != want {
				t.Fatalf("HexDigest = %q, want %q", got, want)
			}
			if gotAgain := h.HexDigest(); gotAgain != want {
				t.Fatalf("second HexDigest = %q, want %q", gotAgain, want)
			}
		})
	}
}

func TestHasherReset(t *testing.T) {
	h := contenthash.New()
	_, err := h.Write([]byte("first"))
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	h.Reset()

	_, err = h.Write([]byte("second"))
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}

	want := referenceContentHash([]byte("second"))
	if got := h.HexDigest(); got != want {
		t.Fatalf("HexDigest after Reset = %q, want %q", got, want)
	}

	h.Reset()
	_, err = h.Write(deterministicBytes(contenthash.BlockSize))
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	h.Reset()
	if got, want := h.HexDigest(), referenceContentHash(nil); got != want {
		t.Fatalf("HexDigest after flushed block Reset = %q, want %q", got, want)
	}
}

func TestHasherZeroValue(t *testing.T) {
	var h contenthash.Hasher

	if got, want := h.HexDigest(), referenceContentHash(nil); got != want {
		t.Fatalf("zero value HexDigest = %q, want %q", got, want)
	}

	_, err := h.Write([]byte("zero value"))
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}

	want := referenceContentHash([]byte("zero value"))
	if got := h.HexDigest(); got != want {
		t.Fatalf("zero value HexDigest after Write = %q, want %q", got, want)
	}

	h.Reset()
	if got, want := h.HexDigest(), referenceContentHash(nil); got != want {
		t.Fatalf("zero value HexDigest after Reset = %q, want %q", got, want)
	}
}

func TestHasherHashInterfaceProperties(t *testing.T) {
	h := contenthash.New()
	if got := h.Size(); got != sha256.Size {
		t.Fatalf("Size = %d, want %d", got, sha256.Size)
	}
	if got := h.BlockSize(); got != contenthash.BlockSize {
		t.Fatalf("BlockSize = %d, want %d", got, contenthash.BlockSize)
	}

	prefix := []byte("prefix:")
	sum := h.Sum(prefix)
	if got, want := string(sum[:len(prefix)]), string(prefix); got != want {
		t.Fatalf("Sum prefix = %q, want %q", got, want)
	}
	if got, want := len(sum)-len(prefix), h.Size(); got != want {
		t.Fatalf("Sum appended %d bytes, want %d", got, want)
	}
}

func TestComputeReturnsReadError(t *testing.T) {
	readErr := errors.New("read failed")
	_, err := contenthash.Compute(errorReader{err: readErr})
	if !errors.Is(err, readErr) {
		t.Fatalf("Compute error = %v, want %v", err, readErr)
	}
}

type errorReader struct {
	err error
}

func (r errorReader) Read([]byte) (int, error) {
	return 0, r.err
}

func referenceContentHash(data []byte) string {
	overall := sha256.New()
	for len(data) > 0 {
		n := contenthash.BlockSize
		if len(data) < n {
			n = len(data)
		}

		blockHash := sha256.Sum256(data[:n])
		_, _ = overall.Write(blockHash[:])
		data = data[n:]
	}
	return hex.EncodeToString(overall.Sum(nil))
}

func deterministicBytes(n int) []byte {
	data := make([]byte, n)
	for i := range data {
		data[i] = byte((i*31 + 7) % 251)
	}
	return data
}

func longestTotal(tests [][]int) int {
	longest := 0
	for _, test := range tests {
		total := 0
		for _, n := range test {
			total += n
		}
		if total > longest {
			longest = total
		}
	}
	return longest
}

var _ io.Reader = errorReader{}
